### ISSUE TITLE
Use system memory

### ISSUE THREAD

**Issue by piranna** [damianmr/heroku-node-settings#1]
Use the system memory as value when $WEB_MEMORY so it can be used on other platforms too.

**Comment by damianmr** [comment]
@piranna sorry I wasn't receiving notifications from this repo (I've just changed that!). Do you have any idea on how to do that?

**Comment by piranna** [comment]
System memory should be fetch someway (`os.totalmemory()` is a good candidate) and use that value as default.

**Comment by joeyslack** [comment]
Yes, the OS package will work (installed by default with node).

require('os').totalmem(); //The os.totalmem() method returns the total amount of system memory in bytes as an integer.

require('os').freemem() //The os.freemem() method returns the amount of free system memory in bytes as an integer.

See: https://nodejs.org/api/os.html

**Comment by damianmr** [comment]
Thanks for pointing this out. Currently the initialization script is in bash, so a bash solution would be needed. However, I don't see there's much interest into this feature. Should you still need it I would happily approve a pull request.
