### ISSUE TITLE
Option "--max_executable_size" not found on node v8.0.0

### ISSUE THREAD

**Issue by gregberge** [damianmr/heroku-node-settings#2]
On node v8.0.0, V8 has been upgraded, `--max_executable_size` option disappeared.

I am not an expert in V8, so I don't know if an option replaced it and what is the best to do.

**Comment by oliviertassinari** [comment]
Same issue here!

**Comment by damianmr** [comment]
Yep, would try to look into it. Any recommendation would be appreciated!

**Comment by oliviertassinari** [comment]
I would guess that we can simply remove the option.

**Comment by gregberge** [comment]
@damianmr yes just remove it for now
